sudo: required
services:
  - docker

before_install:
  - docker build -t dariuszdyrda/battleship-api-test -f ./battleship-api/Dockerfile ./battleship-api

script:
  - docker run dariuszdyrda/battleship-api-test npm test -- --exit

after_success:
  - docker build -t dariuszdyrda/battleship-client ./battleship-client
  - docker build -t dariuszdyrda/battleship-nginx ./nginx
  - docker build -t dariuszdyrda/battleship-api ./battleship-api
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push dariuszdyrda/battleship-client
  - docker push dariuszdyrda/battleship-nginx
  - docker push dariuszdyrda/battleship-api

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: Battleship
  env: Battleship-env-1
  bucket_name: elasticbeanstalk-us-east-2-776960816037
  bucket_path: battleship
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
